### ISSUE TITLE
Export Button doesn't work.

### ISSUE THREAD

**Issue by TheyCallMeFatbird** [DoubleF3lix/Armor-Stand-Animator#2]
I made an animation and did the usual things to do. And then when I click Confirm... nothing happens.
Is it broken?

**Comment by DoubleF3lix** [comment]
Just a few things to check:
What version of Blockbench are you on?
Are you in the Animate window? 
Can you see any errors in the debug console? (CTRL+SHIFT+I)
Can you send me your project files so I can take a look?

**Comment by TheyCallMeFatbird** [comment]
Very sorry for the delay, but here;


  1.  Latest
  2.  Yes
  3.  Uncaught TypeError: Cannot read properties of undefined (reading 'position')
    at Dialog.onConfirm (<anonymous>:385:49)
    at Dialog.close (dialog.js:691:22)
    at HTMLButtonElement.<anonymous> (dialog.js:779:11)
  4.


________________________________

**Comment by DoubleF3lix** [comment]
Unfortunately I'm unable to reproduce, so I'd like to check a few things.
Is the armor stand model itself (the root bone) still named `armor_stand`? That is still required to work (mostly because I'm dumb and haven't changed it yet). Also, I don't know if you intended to, but your file didn't attach.

**Comment by TheyCallMeFatbird** [comment]
(Okay first, you're not dumb. You're way smarter than me for creatin this beauty.)
No, I called it "CashierBuy".
So I just re-name it to armor_stand?
________________________________

**Comment by DoubleF3lix** [comment]
Yup, that should do it.
